# Generated by Django 4.2.5 on 2023-09-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='dd-mm-yyyy'),
            preserve_default=False,
        ),
    ]
